LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)


ifeq ($(TARGET_ARCH),arm64)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libDUTUtil-JNI-CN
LOCAL_SRC_FILES := $(LOCAL_MODULE).so
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib64
include $(BUILD_PREBUILT)
else
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libDUTUtil-JNI-CN
LOCAL_SRC_FILES :=lib32/$(lOCAL_MODULE).so
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
include $(BUILD_PREBUILT)
endif
